# Generated by Django 3.0.5 on 2020-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=100, verbose_name='Location')),
                ('date', models.DateField(default='', verbose_name='Дата выполнения заказа')),
                ('start_of_walk', models.TimeField()),
                ('end_of_walk', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('breed', models.CharField(default='', max_length=100, verbose_name='Breed')),
                ('size', models.IntegerField(default=0, verbose_name='Size')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Price')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Accepted', 'Accepted'), ('Running', 'Running'), ('Canceled', 'Canceled')], default='Accepted', max_length=100, null=True, verbose_name='Статус заказа')),
                ('additional_option', models.CharField(blank=True, default='', max_length=200, verbose_name='Дополнительные опции')),
            ],
        ),
    ]
